services:
  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: password

volumes:
  db-data: {}

networks:
  main: {}
