FROM alpine:3.18

RUN apk add --no-cache go git bash postgresql-client coreutils

# Configuring Golang env vars
ENV GOPATH=/go
ENV GOBIN=$GOPATH/bin
RUN mkdir -p $GOBIN

RUN go install github.com/rubenv/sql-migrate/...@latest && \
  cp /go/bin/sql-migrate /usr/local/bin/sql-migrate

COPY ./migrations /migrations

ENTRYPOINT [ "sql-migrate", "up", "--config", "migrations/config/dbconfig.yml" ]